global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.24.16.1:8761']

#  - job_name: 'api-gateway'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.24.16.1:3030']
#
#  - job_name: 'patient-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.24.16.1:3031']
#
#  - job_name: 'doctor-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.24.16.1:3032']
#
#  - job_name: 'appointment-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.24.16.1:3033']
#
#  - job_name: 'availability-slot-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.24.16.1:3034']